### ISSUE TITLE
Error opening file from the logger package

### ISSUE THREAD

**Issue by Shrinidhi-P-ML** [maplelabs/opensearch-scaling-manager#62]
Following error was observed when the code was executed on a fresh environment
 `ubuntu@master-node-1:~/release_v0.1/opensearch-scaling-manager$ go run main.go 
2022/12/07 17:54:40 error opening file: open logs/application.log: no such file or directory
exit status 1`

**Comment by Meghana-R-ML** [comment]
Fixed by #108
