### ISSUE TITLE
Endpoint for simulating the shard rebalancing

### ISSUE THREAD

**Issue by Akhil-Nair-ML** [maplelabs/opensearch-scaling-manager#74]
1. Create an endpoint to simulate the shard rebalancing.
2. The Provisioner package should call this endpoint to simulate the shard rebalancing.
3. The simulator should set cluster state as yellow for some time after which it should change the state to green state.
4. The time for which the simulator simulate the shard rebalancing should be random.

**Comment by Meghana-R-ML** [comment]
Fixed #79
